import {Inter} from 'next/font/google'
import 'github-markdown-css'
import './globals.css'

const inter = Inter({subsets: ['latin']})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="markdown-body">
    <body className={`${inter.className} flex flex-col`}>
    <div className="w-11/12 h-auto self-center ">
      <div className="my-8 h-12 w-full rounded bg-sky-500/100"/>
      {children}
    </div>

    </body>
    </html>
  )
}
